package concertbooking;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Main GUI Design
 * @author B00687941 - Michael Coey
 */

public class GUI extends javax.swing.JFrame {
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatingPanel = new javax.swing.JPanel();
        seatA1 = new javax.swing.JButton();
        seatA2 = new javax.swing.JButton();
        seatA3 = new javax.swing.JButton();
        seatA4 = new javax.swing.JButton();
        seatA5 = new javax.swing.JButton();
        seatA6 = new javax.swing.JButton();
        seatA7 = new javax.swing.JButton();
        seatA8 = new javax.swing.JButton();
        seatA9 = new javax.swing.JButton();
        seatA10 = new javax.swing.JButton();
        seatB1 = new javax.swing.JButton();
        seatB2 = new javax.swing.JButton();
        seatB3 = new javax.swing.JButton();
        seatB4 = new javax.swing.JButton();
        seatB5 = new javax.swing.JButton();
        seatB6 = new javax.swing.JButton();
        seatB7 = new javax.swing.JButton();
        seatB8 = new javax.swing.JButton();
        seatB9 = new javax.swing.JButton();
        seatB10 = new javax.swing.JButton();
        seatC1 = new javax.swing.JButton();
        seatC2 = new javax.swing.JButton();
        seatC3 = new javax.swing.JButton();
        seatC4 = new javax.swing.JButton();
        seatC5 = new javax.swing.JButton();
        seatC6 = new javax.swing.JButton();
        seatC7 = new javax.swing.JButton();
        seatC8 = new javax.swing.JButton();
        seatC9 = new javax.swing.JButton();
        seatC10 = new javax.swing.JButton();
        seatD1 = new javax.swing.JButton();
        seatD2 = new javax.swing.JButton();
        seatD3 = new javax.swing.JButton();
        seatD4 = new javax.swing.JButton();
        seatD5 = new javax.swing.JButton();
        seatD6 = new javax.swing.JButton();
        seatD7 = new javax.swing.JButton();
        seatD8 = new javax.swing.JButton();
        seatD9 = new javax.swing.JButton();
        seatD10 = new javax.swing.JButton();
        seatE1 = new javax.swing.JButton();
        seatE2 = new javax.swing.JButton();
        seatE3 = new javax.swing.JButton();
        seatE4 = new javax.swing.JButton();
        seatE5 = new javax.swing.JButton();
        seatE6 = new javax.swing.JButton();
        seatE7 = new javax.swing.JButton();
        seatE8 = new javax.swing.JButton();
        seatE9 = new javax.swing.JButton();
        seatE10 = new javax.swing.JButton();
        seatF1 = new javax.swing.JButton();
        seatF2 = new javax.swing.JButton();
        seatF3 = new javax.swing.JButton();
        seatF4 = new javax.swing.JButton();
        seatF5 = new javax.swing.JButton();
        seatF6 = new javax.swing.JButton();
        seatF7 = new javax.swing.JButton();
        seatF8 = new javax.swing.JButton();
        seatF9 = new javax.swing.JButton();
        seatF10 = new javax.swing.JButton();
        seatG1 = new javax.swing.JButton();
        seatG2 = new javax.swing.JButton();
        seatG3 = new javax.swing.JButton();
        seatG4 = new javax.swing.JButton();
        seatG5 = new javax.swing.JButton();
        seatG6 = new javax.swing.JButton();
        seatG7 = new javax.swing.JButton();
        seatG8 = new javax.swing.JButton();
        seatG9 = new javax.swing.JButton();
        seatG10 = new javax.swing.JButton();
        seatH1 = new javax.swing.JButton();
        seatH2 = new javax.swing.JButton();
        seatH3 = new javax.swing.JButton();
        seatH4 = new javax.swing.JButton();
        seatH5 = new javax.swing.JButton();
        seatH6 = new javax.swing.JButton();
        seatH7 = new javax.swing.JButton();
        seatH8 = new javax.swing.JButton();
        seatH9 = new javax.swing.JButton();
        seatH10 = new javax.swing.JButton();
        seatI1 = new javax.swing.JButton();
        seatI2 = new javax.swing.JButton();
        seatI3 = new javax.swing.JButton();
        seatI4 = new javax.swing.JButton();
        seatI5 = new javax.swing.JButton();
        seatI6 = new javax.swing.JButton();
        seatI7 = new javax.swing.JButton();
        seatI8 = new javax.swing.JButton();
        seatI9 = new javax.swing.JButton();
        seatI10 = new javax.swing.JButton();
        seatingColumn1 = new javax.swing.JLabel();
        seatingColumn2 = new javax.swing.JLabel();
        seatingColumn3 = new javax.swing.JLabel();
        seatingColumn4 = new javax.swing.JLabel();
        seatingColumn5 = new javax.swing.JLabel();
        seatingColumn6 = new javax.swing.JLabel();
        seatingColumn7 = new javax.swing.JLabel();
        seatingColumn8 = new javax.swing.JLabel();
        seatingColumn9 = new javax.swing.JLabel();
        seatingColumn10 = new javax.swing.JLabel();
        seatingBronzeSection = new javax.swing.JLabel();
        seatingSilverSection = new javax.swing.JLabel();
        seatingGoldSection = new javax.swing.JLabel();
        seatingRowA = new javax.swing.JLabel();
        seatingRowB = new javax.swing.JLabel();
        seatingRowC = new javax.swing.JLabel();
        seatingRowD = new javax.swing.JLabel();
        seatingRowE = new javax.swing.JLabel();
        seatingRowF = new javax.swing.JLabel();
        seatingRowG = new javax.swing.JLabel();
        seatingRowH = new javax.swing.JLabel();
        seatingRowI = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        lblSearchByName = new javax.swing.JLabel();
        cmdSearchByName = new javax.swing.JButton();
        txtSearchByName = new javax.swing.JTextField();
        lblSearchBySeat = new javax.swing.JLabel();
        txtSearchBySeat = new javax.swing.JTextField();
        cmdSearchBySeat = new javax.swing.JButton();
        lblControlPanel = new javax.swing.JLabel();
        cmdBookSeats = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dSeatsSold = new javax.swing.JLabel();
        seatsSold = new javax.swing.JLabel();
        dSeatsRemaining = new javax.swing.JLabel();
        seatsRemaining = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileNew = new javax.swing.JMenuItem();
        fileSeparator = new javax.swing.JPopupMenu.Separator();
        fileSave = new javax.swing.JMenuItem();
        fileSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainFrame"); // NOI18N

        seatingPanel.setBackground(new java.awt.Color(255, 255, 255));

        seatA1.setBackground(new java.awt.Color(255, 204, 0));
        seatA1.setForeground(new java.awt.Color(255, 255, 255));
        seatA1.setToolTipText("");

        seatA2.setBackground(new java.awt.Color(255, 204, 0));
        seatA2.setForeground(new java.awt.Color(255, 255, 255));

        seatA3.setBackground(new java.awt.Color(255, 204, 0));
        seatA3.setForeground(new java.awt.Color(255, 255, 255));

        seatA4.setBackground(new java.awt.Color(255, 204, 0));
        seatA4.setForeground(new java.awt.Color(255, 255, 255));

        seatA5.setBackground(new java.awt.Color(255, 204, 0));
        seatA5.setForeground(new java.awt.Color(255, 255, 255));

        seatA6.setBackground(new java.awt.Color(255, 204, 0));
        seatA6.setForeground(new java.awt.Color(255, 255, 255));

        seatA7.setBackground(new java.awt.Color(255, 204, 0));
        seatA7.setForeground(new java.awt.Color(255, 255, 255));

        seatA8.setBackground(new java.awt.Color(255, 204, 0));
        seatA8.setForeground(new java.awt.Color(255, 255, 255));

        seatA9.setBackground(new java.awt.Color(255, 204, 0));
        seatA9.setForeground(new java.awt.Color(255, 255, 255));

        seatA10.setBackground(new java.awt.Color(255, 204, 0));
        seatA10.setForeground(new java.awt.Color(255, 255, 255));

        seatB1.setBackground(new java.awt.Color(255, 204, 0));
        seatB1.setForeground(new java.awt.Color(255, 255, 255));

        seatB2.setBackground(new java.awt.Color(255, 204, 0));
        seatB2.setForeground(new java.awt.Color(255, 255, 255));

        seatB3.setBackground(new java.awt.Color(255, 204, 0));
        seatB3.setForeground(new java.awt.Color(255, 255, 255));

        seatB4.setBackground(new java.awt.Color(255, 204, 0));
        seatB4.setForeground(new java.awt.Color(255, 255, 255));

        seatB5.setBackground(new java.awt.Color(255, 204, 0));
        seatB5.setForeground(new java.awt.Color(255, 255, 255));

        seatB6.setBackground(new java.awt.Color(255, 204, 0));
        seatB6.setForeground(new java.awt.Color(255, 255, 255));

        seatB7.setBackground(new java.awt.Color(255, 204, 0));
        seatB7.setForeground(new java.awt.Color(255, 255, 255));

        seatB8.setBackground(new java.awt.Color(255, 204, 0));
        seatB8.setForeground(new java.awt.Color(255, 255, 255));

        seatB9.setBackground(new java.awt.Color(255, 204, 0));
        seatB9.setForeground(new java.awt.Color(255, 255, 255));

        seatB10.setBackground(new java.awt.Color(255, 204, 0));
        seatB10.setForeground(new java.awt.Color(255, 255, 255));

        seatC1.setBackground(new java.awt.Color(255, 204, 0));
        seatC1.setForeground(new java.awt.Color(255, 255, 255));

        seatC2.setBackground(new java.awt.Color(255, 204, 0));
        seatC2.setForeground(new java.awt.Color(255, 255, 255));

        seatC3.setBackground(new java.awt.Color(255, 204, 0));
        seatC3.setForeground(new java.awt.Color(255, 255, 255));

        seatC4.setBackground(new java.awt.Color(255, 204, 0));
        seatC4.setForeground(new java.awt.Color(255, 255, 255));

        seatC5.setBackground(new java.awt.Color(255, 204, 0));
        seatC5.setForeground(new java.awt.Color(255, 255, 255));

        seatC6.setBackground(new java.awt.Color(255, 204, 0));
        seatC6.setForeground(new java.awt.Color(255, 255, 255));

        seatC7.setBackground(new java.awt.Color(255, 204, 0));
        seatC7.setForeground(new java.awt.Color(255, 255, 255));

        seatC8.setBackground(new java.awt.Color(255, 204, 0));
        seatC8.setForeground(new java.awt.Color(255, 255, 255));

        seatC9.setBackground(new java.awt.Color(255, 204, 0));
        seatC9.setForeground(new java.awt.Color(255, 255, 255));

        seatC10.setBackground(new java.awt.Color(255, 204, 0));
        seatC10.setForeground(new java.awt.Color(255, 255, 255));

        seatD1.setBackground(new java.awt.Color(204, 204, 204));
        seatD1.setForeground(new java.awt.Color(255, 255, 255));

        seatD2.setBackground(new java.awt.Color(204, 204, 204));
        seatD2.setForeground(new java.awt.Color(255, 255, 255));

        seatD3.setBackground(new java.awt.Color(204, 204, 204));
        seatD3.setForeground(new java.awt.Color(255, 255, 255));

        seatD4.setBackground(new java.awt.Color(204, 204, 204));
        seatD4.setForeground(new java.awt.Color(255, 255, 255));

        seatD5.setBackground(new java.awt.Color(204, 204, 204));
        seatD5.setForeground(new java.awt.Color(255, 255, 255));

        seatD6.setBackground(new java.awt.Color(204, 204, 204));
        seatD6.setForeground(new java.awt.Color(255, 255, 255));

        seatD7.setBackground(new java.awt.Color(204, 204, 204));
        seatD7.setForeground(new java.awt.Color(255, 255, 255));

        seatD8.setBackground(new java.awt.Color(204, 204, 204));
        seatD8.setForeground(new java.awt.Color(255, 255, 255));

        seatD9.setBackground(new java.awt.Color(204, 204, 204));
        seatD9.setForeground(new java.awt.Color(255, 255, 255));

        seatD10.setBackground(new java.awt.Color(204, 204, 204));
        seatD10.setForeground(new java.awt.Color(255, 255, 255));

        seatE1.setBackground(new java.awt.Color(204, 204, 204));
        seatE1.setForeground(new java.awt.Color(255, 255, 255));

        seatE2.setBackground(new java.awt.Color(204, 204, 204));
        seatE2.setForeground(new java.awt.Color(255, 255, 255));

        seatE3.setBackground(new java.awt.Color(204, 204, 204));
        seatE3.setForeground(new java.awt.Color(255, 255, 255));

        seatE4.setBackground(new java.awt.Color(204, 204, 204));
        seatE4.setForeground(new java.awt.Color(255, 255, 255));

        seatE5.setBackground(new java.awt.Color(204, 204, 204));
        seatE5.setForeground(new java.awt.Color(255, 255, 255));

        seatE6.setBackground(new java.awt.Color(204, 204, 204));
        seatE6.setForeground(new java.awt.Color(255, 255, 255));

        seatE7.setBackground(new java.awt.Color(204, 204, 204));
        seatE7.setForeground(new java.awt.Color(255, 255, 255));

        seatE8.setBackground(new java.awt.Color(204, 204, 204));
        seatE8.setForeground(new java.awt.Color(255, 255, 255));

        seatE9.setBackground(new java.awt.Color(204, 204, 204));
        seatE9.setForeground(new java.awt.Color(255, 255, 255));

        seatE10.setBackground(new java.awt.Color(204, 204, 204));
        seatE10.setForeground(new java.awt.Color(255, 255, 255));

        seatF1.setBackground(new java.awt.Color(204, 204, 204));
        seatF1.setForeground(new java.awt.Color(255, 255, 255));

        seatF2.setBackground(new java.awt.Color(204, 204, 204));
        seatF2.setForeground(new java.awt.Color(255, 255, 255));

        seatF3.setBackground(new java.awt.Color(204, 204, 204));
        seatF3.setForeground(new java.awt.Color(255, 255, 255));

        seatF4.setBackground(new java.awt.Color(204, 204, 204));
        seatF4.setForeground(new java.awt.Color(255, 255, 255));

        seatF5.setBackground(new java.awt.Color(204, 204, 204));
        seatF5.setForeground(new java.awt.Color(255, 255, 255));

        seatF6.setBackground(new java.awt.Color(204, 204, 204));
        seatF6.setForeground(new java.awt.Color(255, 255, 255));

        seatF7.setBackground(new java.awt.Color(204, 204, 204));
        seatF7.setForeground(new java.awt.Color(255, 255, 255));

        seatF8.setBackground(new java.awt.Color(204, 204, 204));
        seatF8.setForeground(new java.awt.Color(255, 255, 255));

        seatF9.setBackground(new java.awt.Color(204, 204, 204));
        seatF9.setForeground(new java.awt.Color(255, 255, 255));

        seatF10.setBackground(new java.awt.Color(204, 204, 204));
        seatF10.setForeground(new java.awt.Color(255, 255, 255));

        seatG1.setBackground(new java.awt.Color(204, 102, 0));
        seatG1.setForeground(new java.awt.Color(255, 255, 255));

        seatG2.setBackground(new java.awt.Color(204, 102, 0));
        seatG2.setForeground(new java.awt.Color(255, 255, 255));

        seatG3.setBackground(new java.awt.Color(204, 102, 0));
        seatG3.setForeground(new java.awt.Color(255, 255, 255));

        seatG4.setBackground(new java.awt.Color(204, 102, 0));
        seatG4.setForeground(new java.awt.Color(255, 255, 255));

        seatG5.setBackground(new java.awt.Color(204, 102, 0));
        seatG5.setForeground(new java.awt.Color(255, 255, 255));

        seatG6.setBackground(new java.awt.Color(204, 102, 0));
        seatG6.setForeground(new java.awt.Color(255, 255, 255));

        seatG7.setBackground(new java.awt.Color(204, 102, 0));
        seatG7.setForeground(new java.awt.Color(255, 255, 255));

        seatG8.setBackground(new java.awt.Color(204, 102, 0));
        seatG8.setForeground(new java.awt.Color(255, 255, 255));

        seatG9.setBackground(new java.awt.Color(204, 102, 0));
        seatG9.setForeground(new java.awt.Color(255, 255, 255));

        seatG10.setBackground(new java.awt.Color(204, 102, 0));
        seatG10.setForeground(new java.awt.Color(255, 255, 255));

        seatH1.setBackground(new java.awt.Color(204, 102, 0));
        seatH1.setForeground(new java.awt.Color(255, 255, 255));

        seatH2.setBackground(new java.awt.Color(204, 102, 0));
        seatH2.setForeground(new java.awt.Color(255, 255, 255));

        seatH3.setBackground(new java.awt.Color(204, 102, 0));
        seatH3.setForeground(new java.awt.Color(255, 255, 255));

        seatH4.setBackground(new java.awt.Color(204, 102, 0));
        seatH4.setForeground(new java.awt.Color(255, 255, 255));

        seatH5.setBackground(new java.awt.Color(204, 102, 0));
        seatH5.setForeground(new java.awt.Color(255, 255, 255));

        seatH6.setBackground(new java.awt.Color(204, 102, 0));
        seatH6.setForeground(new java.awt.Color(255, 255, 255));

        seatH7.setBackground(new java.awt.Color(204, 102, 0));
        seatH7.setForeground(new java.awt.Color(255, 255, 255));

        seatH8.setBackground(new java.awt.Color(204, 102, 0));
        seatH8.setForeground(new java.awt.Color(255, 255, 255));

        seatH9.setBackground(new java.awt.Color(204, 102, 0));
        seatH9.setForeground(new java.awt.Color(255, 255, 255));

        seatH10.setBackground(new java.awt.Color(204, 102, 0));
        seatH10.setForeground(new java.awt.Color(255, 255, 255));

        seatI1.setBackground(new java.awt.Color(204, 102, 0));
        seatI1.setForeground(new java.awt.Color(255, 255, 255));

        seatI2.setBackground(new java.awt.Color(204, 102, 0));
        seatI2.setForeground(new java.awt.Color(255, 255, 255));

        seatI3.setBackground(new java.awt.Color(204, 102, 0));
        seatI3.setForeground(new java.awt.Color(255, 255, 255));

        seatI4.setBackground(new java.awt.Color(204, 102, 0));
        seatI4.setForeground(new java.awt.Color(255, 255, 255));

        seatI5.setBackground(new java.awt.Color(204, 102, 0));
        seatI5.setForeground(new java.awt.Color(255, 255, 255));

        seatI6.setBackground(new java.awt.Color(204, 102, 0));
        seatI6.setForeground(new java.awt.Color(255, 255, 255));

        seatI7.setBackground(new java.awt.Color(204, 102, 0));
        seatI7.setForeground(new java.awt.Color(255, 255, 255));

        seatI8.setBackground(new java.awt.Color(204, 102, 0));
        seatI8.setForeground(new java.awt.Color(255, 255, 255));

        seatI9.setBackground(new java.awt.Color(204, 102, 0));
        seatI9.setForeground(new java.awt.Color(255, 255, 255));

        seatI10.setBackground(new java.awt.Color(204, 102, 0));
        seatI10.setForeground(new java.awt.Color(255, 255, 255));

        seatingColumn1.setText("1");
        seatingColumn1.setToolTipText("");

        seatingColumn2.setText("2");
        seatingColumn2.setToolTipText("");

        seatingColumn3.setText("3");
        seatingColumn3.setToolTipText("");

        seatingColumn4.setText("4");

        seatingColumn5.setText("5");

        seatingColumn6.setText("6");
        seatingColumn6.setToolTipText("");

        seatingColumn7.setText("7");
        seatingColumn7.setToolTipText("");

        seatingColumn8.setText("8");

        seatingColumn9.setText("9");

        seatingColumn10.setText("10");

        seatingBronzeSection.setText("Bronze Section");

        seatingSilverSection.setText("Silver Section");

        seatingGoldSection.setText("Gold Section");

        seatingRowA.setText("A");

        seatingRowB.setText("B");

        seatingRowC.setText("C");

        seatingRowD.setText("D");

        seatingRowE.setText("E");

        seatingRowF.setText("F");

        seatingRowG.setText("G");

        seatingRowH.setText("H");

        seatingRowI.setText("I");

        javax.swing.GroupLayout seatingPanelLayout = new javax.swing.GroupLayout(seatingPanel);
        seatingPanel.setLayout(seatingPanelLayout);
        seatingPanelLayout.setHorizontalGroup(
            seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatingPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(seatingGoldSection)
                        .addGap(18, 18, 18)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seatA10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seatA9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seatA8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seatA7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seatA6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addComponent(seatC10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatC9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addComponent(seatB10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatF5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatF4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatF3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatF2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatE5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatD5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatingRowE)
                                    .addComponent(seatingRowF)
                                    .addComponent(seatingRowD)))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatB5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(seatA5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seatingColumn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatA4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatingColumn4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(seatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatingColumn3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                                .addComponent(seatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatingPanelLayout.createSequentialGroup()
                                                    .addComponent(seatingColumn2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seatingColumn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(seatingPanelLayout.createSequentialGroup()
                                                    .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(seatingRowA)
                                                        .addComponent(seatingRowB))))))
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(seatingRowC))))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatG5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatG4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatG3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatG2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatG1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(seatH5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatI5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seatH4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatI4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seatH3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatI3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                                .addComponent(seatH2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seatH1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                                .addComponent(seatI2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seatI1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seatingRowG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seatingRowH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seatingRowI, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addComponent(seatingBronzeSection)
                        .addGap(18, 18, 18)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addComponent(seatG10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatG9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatG8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatG7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatG6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatI10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seatI9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatH10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatH9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatH8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatI8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatH7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatI7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatH6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatI6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(seatingSilverSection)
                        .addGap(18, 18, 18)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seatF10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatE10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatD9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatE9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatD8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatingPanelLayout.createSequentialGroup()
                                        .addComponent(seatE8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatE6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(seatingPanelLayout.createSequentialGroup()
                                .addComponent(seatF9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatF8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatF7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatF6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        seatingPanelLayout.setVerticalGroup(
            seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatingPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatingColumn10)
                    .addComponent(seatingColumn9)
                    .addComponent(seatingColumn8)
                    .addComponent(seatingColumn7)
                    .addComponent(seatingColumn6)
                    .addComponent(seatingColumn5)
                    .addComponent(seatingColumn4)
                    .addComponent(seatingColumn2)
                    .addComponent(seatingColumn1)
                    .addComponent(seatingColumn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seatA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatA10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatingRowA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatB9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatB10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(seatingGoldSection))
                    .addComponent(seatB5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatingRowB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatingRowC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatD6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seatE9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seatE10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seatE8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seatE7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seatE6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seatingSilverSection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatF6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatD1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatingRowD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seatE5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatE4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatingRowE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatF2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatF5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seatF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seatingRowF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatG10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatG9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatG8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatG7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatG6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatH6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seatingBronzeSection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatI10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatI9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatI8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatI7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatI6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(seatingPanelLayout.createSequentialGroup()
                        .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seatG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatG4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatingRowG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatingRowH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(seatingPanelLayout.createSequentialGroup()
                            .addComponent(seatG5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(seatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatH4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatH1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seatI5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(seatI4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatI3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatI2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatI1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatingRowI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        controlPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblSearchByName.setText("Search By Name");

        cmdSearchByName.setText("Search");

        txtSearchByName.setToolTipText("Enter name to search here");

        lblSearchBySeat.setText("Search By Seat");

        cmdSearchBySeat.setText("Search");

        lblControlPanel.setText("Control Panel");

        cmdBookSeats.setText("Confirm Booking");
        cmdBookSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBookSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(lblSearchByName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchByName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdSearchByName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmdSearchBySeat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                        .addComponent(lblSearchBySeat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSearchBySeat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblControlPanel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdBookSeats)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblControlPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBookSeats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchByName)
                    .addComponent(txtSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSearchByName)
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchBySeat)
                    .addComponent(txtSearchBySeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSearchBySeat)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        dSeatsSold.setBackground(new java.awt.Color(255, 255, 255));
        dSeatsSold.setText("Seats Sold = ");

        dSeatsRemaining.setBackground(new java.awt.Color(255, 255, 255));
        dSeatsRemaining.setText("Seats Remaining = ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dSeatsSold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatsSold, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dSeatsRemaining)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatsRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dSeatsSold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seatsSold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dSeatsRemaining, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(seatsRemaining, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        menuBar.setName(""); // NOI18N

        menuFile.setText("File");

        fileNew.setText("New Concert");
        menuFile.add(fileNew);
        menuFile.add(fileSeparator);

        fileSave.setText("Save");
        menuFile.add(fileSave);
        menuFile.add(fileSeparator1);

        fileExit.setText("Exit");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        menuFile.add(fileExit);

        menuBar.add(menuFile);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void paint(Graphics g) 
   {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        
        //Drawing fire exit left
        g2.drawLine(50, 80, 125, 80);
        g2.drawLine(175, 80, 250, 80);
        g2.drawString("Fire Exit", 129, 75);
        
        //Drawing main stage section
        g2.drawLine(250, 80, 250, 125);   
        g2.drawLine(400, 125, 250, 125); 
        g2.drawLine(400, 80, 400, 125);
        g2.drawString("Stage", 310, 115);
    
        //Drawing fire exit right
        g2.drawLine(400, 80, 475, 80);
        g2.drawString("Fire Exit", 478, 75);
        g2.drawLine(525, 80, 600, 80);
        
        //Drawing main entrance section
        g2.drawLine(50, 500, 275, 500);
        g2.drawLine(350, 500, 600, 500);
        g2.drawString("Main Entrance", 275, 490);
   }
    
    
   //Code to display price of concert onto the seats 
   private void setToolTipTextSeats()
   {
       //Gold seats
       seatA1.setToolTipText("");
       seatA2.setToolTipText("");
       seatA3.setToolTipText("");
       seatA4.setToolTipText("");
       seatA5.setToolTipText("");
       seatA6.setToolTipText("");
       seatA7.setToolTipText("");
       seatA8.setToolTipText("");
       seatA9.setToolTipText("");
       seatA10.setToolTipText("");
       
       seatB1.setToolTipText("");
       seatB2.setToolTipText("");
       seatB3.setToolTipText("");
       seatB4.setToolTipText("");
       seatB5.setToolTipText("");
       seatB6.setToolTipText("");
       seatB7.setToolTipText("");
       seatB8.setToolTipText("");
       seatB9.setToolTipText("");
       seatB10.setToolTipText("");
       
       seatC1.setToolTipText("");
       seatC2.setToolTipText("");
       seatC3.setToolTipText("");
       seatC4.setToolTipText("");
       seatC5.setToolTipText("");
       seatC6.setToolTipText("");
       seatC7.setToolTipText("");
       seatC8.setToolTipText("");
       seatC9.setToolTipText("");
       seatC10.setToolTipText("");
       
       //Silver seats
       seatD1.setToolTipText("");
       seatD2.setToolTipText("");
       seatD3.setToolTipText("");
       seatD4.setToolTipText("");
       seatD5.setToolTipText("");
       seatD6.setToolTipText("");
       seatD7.setToolTipText("");
       seatD8.setToolTipText("");
       seatD9.setToolTipText("");
       seatD10.setToolTipText("");
       
       seatE1.setToolTipText("");
       seatE2.setToolTipText("");
       seatE3.setToolTipText("");
       seatE4.setToolTipText("");
       seatE5.setToolTipText("");
       seatE6.setToolTipText("");
       seatE7.setToolTipText("");
       seatE8.setToolTipText("");
       seatE9.setToolTipText("");
       seatE10.setToolTipText("");
       
       seatF1.setToolTipText("");
       seatF2.setToolTipText("");
       seatF3.setToolTipText("");
       seatF4.setToolTipText("");
       seatF5.setToolTipText("");
       seatF6.setToolTipText("");
       seatF7.setToolTipText("");
       seatF8.setToolTipText("");
       seatF9.setToolTipText("");
       seatF10.setToolTipText("");
       
       //Bronze seats
       seatG1.setToolTipText("");
       seatG2.setToolTipText("");
       seatG3.setToolTipText("");
       seatG4.setToolTipText("");
       seatG5.setToolTipText("");
       seatG6.setToolTipText("");
       seatG7.setToolTipText("");
       seatG8.setToolTipText("");
       seatG9.setToolTipText("");
       seatG10.setToolTipText("");
       
       seatH1.setToolTipText("");
       seatH2.setToolTipText("");
       seatH3.setToolTipText("");
       seatH4.setToolTipText("");
       seatH5.setToolTipText("");
       seatH6.setToolTipText("");
       seatH7.setToolTipText("");
       seatH8.setToolTipText("");
       seatH9.setToolTipText("");
       seatH10.setToolTipText("");
       
       seatI1.setToolTipText("");
       seatI2.setToolTipText("");
       seatI3.setToolTipText("");
       seatI4.setToolTipText("");
       seatI5.setToolTipText("");
       seatI6.setToolTipText("");
       seatI7.setToolTipText("");
       seatI8.setToolTipText("");
       seatI9.setToolTipText("");
       seatI10.setToolTipText("");
   }
   
   
   
    private void cmdBookSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBookSeatsActionPerformed
        
        //Creating text fields for user input
        JTextField txtCustomerName = new JTextField(20);
        JTextField txtCustomerPhone = new JTextField(20);
        JTextField txtCustomerEmail = new JTextField(20);
        
        //Adding input and display label for customer name
        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Customer Name"));
        myPanel.add(txtCustomerName);
        
        //Adding input and display label for customer phone
        myPanel.add(new JLabel("Customer Phone"));
        myPanel.add(txtCustomerPhone);
        
        //Adding input and display label for customer email
        myPanel.add(new JLabel("Customer Email"));
        myPanel.add(txtCustomerEmail); 
        
        //Setting option pane to display contents below each other
        myPanel.setLayout(new BoxLayout(myPanel, BoxLayout.Y_AXIS));
        
        //Setting layout of option pane to be OK/Cancel as well as title
        int result = JOptionPane.showConfirmDialog(null, myPanel, "Please Enter Customer Details", JOptionPane.OK_CANCEL_OPTION);
        
        //Setting option pane to save customer/seats into program
        if(result == JOptionPane.OK_OPTION)
        {
            String customerName = txtCustomerName.getText();
            String customerPhone = txtCustomerPhone.getText();
            String customerEmail = txtCustomerEmail.getText();
            
//THIS IS IMPORTANT *********************************************************************************
            //****************************
            //Customer customer = new Customer(customerName, customerPhone, customerEmail); 
        }
        
    }//GEN-LAST:event_cmdBookSeatsActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        
        //Setting exit pannel to close program
        JPanel exitMenu = new JPanel();
        exitMenu.add(new JLabel("Are you sure you want to exit?"));
        
        int result = JOptionPane.showConfirmDialog(null, exitMenu, "Exit Program?", JOptionPane.OK_CANCEL_OPTION);
        System.exit(0);
        
        
        if(result == JOptionPane.OK_OPTION)
        {
            System.exit(0);
        
        }
        
    }//GEN-LAST:event_fileExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBookSeats;
    private javax.swing.JButton cmdSearchByName;
    private javax.swing.JButton cmdSearchBySeat;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel dSeatsRemaining;
    private javax.swing.JLabel dSeatsSold;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileNew;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JPopupMenu.Separator fileSeparator;
    private javax.swing.JPopupMenu.Separator fileSeparator1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblControlPanel;
    private javax.swing.JLabel lblSearchByName;
    private javax.swing.JLabel lblSearchBySeat;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JButton seatA1;
    private javax.swing.JButton seatA10;
    private javax.swing.JButton seatA2;
    private javax.swing.JButton seatA3;
    private javax.swing.JButton seatA4;
    private javax.swing.JButton seatA5;
    private javax.swing.JButton seatA6;
    private javax.swing.JButton seatA7;
    private javax.swing.JButton seatA8;
    private javax.swing.JButton seatA9;
    private javax.swing.JButton seatB1;
    private javax.swing.JButton seatB10;
    private javax.swing.JButton seatB2;
    private javax.swing.JButton seatB3;
    private javax.swing.JButton seatB4;
    private javax.swing.JButton seatB5;
    private javax.swing.JButton seatB6;
    private javax.swing.JButton seatB7;
    private javax.swing.JButton seatB8;
    private javax.swing.JButton seatB9;
    private javax.swing.JButton seatC1;
    private javax.swing.JButton seatC10;
    private javax.swing.JButton seatC2;
    private javax.swing.JButton seatC3;
    private javax.swing.JButton seatC4;
    private javax.swing.JButton seatC5;
    private javax.swing.JButton seatC6;
    private javax.swing.JButton seatC7;
    private javax.swing.JButton seatC8;
    private javax.swing.JButton seatC9;
    private javax.swing.JButton seatD1;
    private javax.swing.JButton seatD10;
    private javax.swing.JButton seatD2;
    private javax.swing.JButton seatD3;
    private javax.swing.JButton seatD4;
    private javax.swing.JButton seatD5;
    private javax.swing.JButton seatD6;
    private javax.swing.JButton seatD7;
    private javax.swing.JButton seatD8;
    private javax.swing.JButton seatD9;
    private javax.swing.JButton seatE1;
    private javax.swing.JButton seatE10;
    private javax.swing.JButton seatE2;
    private javax.swing.JButton seatE3;
    private javax.swing.JButton seatE4;
    private javax.swing.JButton seatE5;
    private javax.swing.JButton seatE6;
    private javax.swing.JButton seatE7;
    private javax.swing.JButton seatE8;
    private javax.swing.JButton seatE9;
    private javax.swing.JButton seatF1;
    private javax.swing.JButton seatF10;
    private javax.swing.JButton seatF2;
    private javax.swing.JButton seatF3;
    private javax.swing.JButton seatF4;
    private javax.swing.JButton seatF5;
    private javax.swing.JButton seatF6;
    private javax.swing.JButton seatF7;
    private javax.swing.JButton seatF8;
    private javax.swing.JButton seatF9;
    private javax.swing.JButton seatG1;
    private javax.swing.JButton seatG10;
    private javax.swing.JButton seatG2;
    private javax.swing.JButton seatG3;
    private javax.swing.JButton seatG4;
    private javax.swing.JButton seatG5;
    private javax.swing.JButton seatG6;
    private javax.swing.JButton seatG7;
    private javax.swing.JButton seatG8;
    private javax.swing.JButton seatG9;
    private javax.swing.JButton seatH1;
    private javax.swing.JButton seatH10;
    private javax.swing.JButton seatH2;
    private javax.swing.JButton seatH3;
    private javax.swing.JButton seatH4;
    private javax.swing.JButton seatH5;
    private javax.swing.JButton seatH6;
    private javax.swing.JButton seatH7;
    private javax.swing.JButton seatH8;
    private javax.swing.JButton seatH9;
    private javax.swing.JButton seatI1;
    private javax.swing.JButton seatI10;
    private javax.swing.JButton seatI2;
    private javax.swing.JButton seatI3;
    private javax.swing.JButton seatI4;
    private javax.swing.JButton seatI5;
    private javax.swing.JButton seatI6;
    private javax.swing.JButton seatI7;
    private javax.swing.JButton seatI8;
    private javax.swing.JButton seatI9;
    private javax.swing.JLabel seatingBronzeSection;
    private javax.swing.JLabel seatingColumn1;
    private javax.swing.JLabel seatingColumn10;
    private javax.swing.JLabel seatingColumn2;
    private javax.swing.JLabel seatingColumn3;
    private javax.swing.JLabel seatingColumn4;
    private javax.swing.JLabel seatingColumn5;
    private javax.swing.JLabel seatingColumn6;
    private javax.swing.JLabel seatingColumn7;
    private javax.swing.JLabel seatingColumn8;
    private javax.swing.JLabel seatingColumn9;
    private javax.swing.JLabel seatingGoldSection;
    private javax.swing.JPanel seatingPanel;
    private javax.swing.JLabel seatingRowA;
    private javax.swing.JLabel seatingRowB;
    private javax.swing.JLabel seatingRowC;
    private javax.swing.JLabel seatingRowD;
    private javax.swing.JLabel seatingRowE;
    private javax.swing.JLabel seatingRowF;
    private javax.swing.JLabel seatingRowG;
    private javax.swing.JLabel seatingRowH;
    private javax.swing.JLabel seatingRowI;
    private javax.swing.JLabel seatingSilverSection;
    private javax.swing.JLabel seatsRemaining;
    private javax.swing.JLabel seatsSold;
    private javax.swing.JTextField txtSearchByName;
    private javax.swing.JTextField txtSearchBySeat;
    // End of variables declaration//GEN-END:variables
}
